---
- name: Download services to localhost
  hosts: localhost
  tasks:
   - name: "Download Elasticsearch's rpm"
     get_url:
       url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elk_stack_version }}-x86_64.rpm"
       dest: ~/
       mode: 0755
   - name: "Download Kibana`s rpm"
     get_url:
       url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ elk_stack_version }}-x86_64.rpm"
       dest: ~/
       mode: 0755
   - name: "Download filebeat rpm"
     get_url:
       url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ elk_stack_version }}-x86_64.rpm"
       dest: ~/
       mode: 0755
  tags: 
    - download
- name: Copy to yandex machine and install elasticsearch
  hosts: el-instance
  tasks:
   - name: Copy Elasticsearch
     copy:
         src: ~/elasticsearch-8.1.2-x86_64.rpm
         dest: /tmp/elasticsearch-{{ elk_stack_version }}-x86_64.rpm
         owner: vagrant
         group: vagrant
         mode: 0644
     register: download_elastic
- name: Install Elasticsearch
  hosts: el-instance
  handlers:
      - name: restart Elasticsearch
        become: true
        service:
          name: elasticsearch
          state: restarted
  tasks:
      - name: Install Elasticsearch
        become: true
        yum:
          name: "/tmp/elasticsearch-{{ elk_stack_version }}-x86_64.rpm"
          state: present
      - name: Configure Elasticsearch
        become: true
        template:
          src: elasticsearch.yml.j2
          dest: /etc/elasticsearch/elasticsearch.yml
          mode: 0755
        notify: restart Elasticsearch
- name: Copy to yandex machine and install kibana
  hosts: ki-instance
  tasks:
   - name: Copy kibana
     copy:
         src: ~/kibana-8.1.2-x86_64.rpm
         dest: /tmp/kibana-{{ elk_stack_version }}-x86_64.rpm
         owner: vagrant
         group: vagrant
         mode: 0644
     register: download_elastic 
- name: Install kibana
  hosts: ki-instance
  handlers:
      - name: restart kibana
        become: true
        service:
          name: kibana
          state: restarted
  tasks:
      - name: Install kibana
        become: true
        yum:
          name: "/tmp/kibana-{{ elk_stack_version }}-x86_64.rpm"
          state: present
      - name: Configure kibana
        become: true
        template:
          src: kibana.yml.j2
          dest: /etc/kibana/kibana.yml
          mode: 0755
        notify: restart kibana
- name: Copy to yandex machine and install filebeat
  hosts: fb-instance
  tasks:
   - name: Copy filebeat
     copy:
         src: ~/filebeat-8.1.2-x86_64.rpm
         dest: /tmp/filebeat-{{ elk_stack_version }}-x86_64.rpm
         owner: vagrant
         group: vagrant
         mode: 0644
     register: download_filebeat 
- name: Install filebeat
  hosts: fb-instance
  handlers:
      - name: restart filebeat
        become: true
        service:
          name: filebeat
          state: restarted
  tasks:
      - name: Install filebeat
        become: true
        yum:
          name: "/tmp/filebeat-{{ elk_stack_version }}-x86_64.rpm"
          state: present
      - name: Configure filebeat
        become: true
        template:
           src: filebeat.yml.j2
           dest: /etc/filebeat/filebeat.yml
           mode: 0755
        notify: restart filebeat
      - name: set filebeat systemwork
        become: true
        command:
          cmd: filebeat modules enable system
          chdir: /usr/share/filebeat/bin
        register: filebeat_modules
        changed_when: filebeat_modules.stdout != 'Module system is already enabled'
      - name: load kibana dashboard
        become: true
        command:
          cmd: filebeat setup
          chdir: /usr/share/filebeat/bin
        register: filebeat_setup
        changed_when: false
        until: filebeat_setup is succeeded
